name: "Build & Deploy"
on:
  push:
    branches:
      - main

jobs:
  build:
    name: "Build & Deploy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install yarn -g
      - name: Build App
        run: |
          yarn
          yarn build
              - name: 📂 Sync files
      - uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist
